import { useMemo, useState } from "react";
import { osintTools, OSINT_TOOL_SCENARIOS } from "../data/osintTools";
export default function ToolLibrary(){
 const [query,setQuery]=useState(""); const [tool,setTool]=useState("all");
 const tools=useMemo(()=>{const q=query.toLowerCase().trim();return osintTools.filter(x=>(tool==="all"||x.name===tool)&&(!q||Object.values(x).flat().join(" ").toLowerCase().includes(q)))},[query,tool]);
 const scenarios=useMemo(()=>OSINT_TOOL_SCENARIOS.filter(x=>tool==="all"||x.tool===tool),[tool]);
 return <div className="space-y-4">
  <div className="flex flex-wrap gap-2"><input aria-label="Search tools" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tools and capabilities..." className="h-9 min-w-56 flex-1 rounded-md border border-slate-300 bg-slate-50 px-3 text-xs outline-none focus:border-emerald-500 focus:bg-white"/><select aria-label="Filter tool" value={tool} onChange={e=>setTool(e.target.value)} className="h-9 rounded-md border border-slate-300 bg-white px-3 text-xs">{["all",...osintTools.map(x=>x.name)].map(x=><option key={x} value={x}>{x==="all"?"All tools":x}</option>)}</select></div>
  <section className="grid gap-3 lg:grid-cols-2">{tools.map(x=><article key={x.id} className="rounded-lg border border-slate-200 bg-white p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-bold text-slate-900">{x.name}</h3><p className="mt-1 text-xs text-slate-500">{x.purpose}</p></div><span className="rounded bg-slate-100 px-2 py-1 text-[9px] font-bold uppercase text-slate-500">{x.category}</span></div><div className="mt-4 grid gap-3 md:grid-cols-2"><ToolField title="Typical input" text={x.typicalInput}/><ToolField title="Typical output" text={x.typicalOutput}/><ToolField title="Safe use" text={x.safeUse}/><ToolField title="Evidence produced" text={x.evidenceProduced}/><ToolField title="Limitations" text={x.limitations}/><ToolField title="Related tools" text={x.relatedTools.join(", ")}/></div></article>)}</section>
  <section className="overflow-hidden rounded-lg border border-slate-200 bg-white"><div className="border-b border-slate-200 bg-slate-50 px-4 py-3"><p className="text-xs font-bold text-slate-900">Tool scenarios</p><p className="mt-0.5 text-[11px] text-slate-500">{scenarios.length} deterministic scenarios</p></div><div className="divide-y divide-slate-100">{scenarios.map(x=><details key={x.id} className="group px-4 py-3"><summary className="cursor-pointer list-none"><div className="flex items-center gap-2"><span className="rounded bg-emerald-50 px-1.5 py-0.5 text-[9px] font-bold text-emerald-700">{x.id}</span><span className="text-xs font-semibold text-slate-800">{x.tool}</span><span className="text-xs text-slate-500">— {x.situation}</span></div></summary><div className="mt-3 grid gap-3 pl-2 text-xs text-slate-600 md:grid-cols-2"><p><b>Objective:</b> {x.objective}</p><p><b>Input:</b> {x.input}</p><p><b>Expected:</b> {x.expectedObservation}</p><p><b>Validation:</b> {x.validation}</p><p><b>Evidence:</b> {x.evidence}</p><p><b>Limitations:</b> {x.limitations}</p><p><b>Next:</b> {x.nextStep}</p><p><b>Stop:</b> {x.stopCondition}</p></div></details>)}</div></section>
 </div>;
}
function ToolField({title,text}:{title:string;text:string}){return <div><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">{title}</p><p className="mt-1 text-xs leading-5 text-slate-600">{text}</p></div>}
